### PR TITLE
Add legend

### PR DESCRIPTION
**Pull request by RyanMarshall5765**
Adds legend to the map. Currently color coded span boxes. Looking into making them the monastery Icons without spacing issues.

PR to resolve: #30

### CODE REVIEW

**Comment by joephayes** [comment]
@RyanMarshall5765 - as per our discussion, I would like to see this generate the legend based on the map's data. Do we want to do that as a separate issue?

**Comment by joephayes** [comment]
@RyanMarshall5765 - do you want to add the monastery icons to this PR or should that be a different issue?

**Comment by joephayes** [comment]
@RyanMarshall5765 - overall, this looks good! Two things:

1. Is it possible to have the legend to have a white or translucent background panel?
1. Is it possible to show the monastery icons in the legend?

**Comment by RyanMarshall5765** [comment]
@joephayes 
1. Wasn't sure if you wanted one so I went without to be safe. Trying to do it now but for some reason it works in plain HTML but not when in the project. Looking into why now.

2. Also trying to figure this one out because it messes up with spacing. Figured I would move this in when I figured it out or we added other types of places like Castles and so on.

**Comment by RyanMarshall5765** [comment]
screen shot 2019-02-05 at 4 11 52 pm
@joephayes How does this look?

**Comment by joephayes** [comment]
@RyanMarshall5765 - better - can you make it an off white? Or partially translucent?

**Comment by RyanMarshall5765** [comment]
screen shot 2019-02-05 at 4 46 16 pm
@joephayes  What I just pushed.

**Comment by joephayes** [comment]
Looks great! Please squash and merge!

**Pull request merged**
